#!/usr/bin/env python3
import time
from playwright.async_api import Page, Locator
from typing import List, Dict, Any

class ContactFormTester:
    """
    Responsibility: Automated testing of detected contact and support forms.
    """
    async def test(self, page: Page, form_locator: Locator, fields: List[Dict[str, Any]]) -> Dict[str, Any]:
        start_time = time.time()
        messages = []
        errors = []
        screenshot_bytes = None
        success = False

        try:
            # 1. Populate form elements using context-appropriate text payloads
            for field in fields:
                field_locator = form_locator.locator(f"{field['tag']}[name='{field['name']}']").first if field['name'] else None
                if not field_locator or not await field_locator.is_visible():
                    continue

                ftype = field['type']
                if ftype == "email":
                    await field_locator.fill("test_sentinel@example.com")
                elif ftype in ["tel", "phone"]:
                    await field_locator.fill("+1234567890")
                elif ftype == "textarea" or "message" in field['name'].lower():
                    await field_locator.fill("This is an automated functional integration check generated by WebSentinel framework.")
                elif ftype in ["text", "textarea"]:
                    await field_locator.fill("WebSentinel Test Input")

            # 2. Capture a pre-submission snapshot
            messages.append("Contact form inputs populated successfully.")
            
            # 3. Locate and click submission element
            submit_btn = form_locator.locator("button[type='submit'], input[type='submit'], button:has-text('Submit'), button:has-text('Send')").first
            initial_url = page.url
            
            if await submit_btn.is_visible():
                messages.append("Triggering contact form submission click event.")
                await submit_btn.click(timeout=1500, no_wait_after=True)
                await page.wait_for_timeout(1000)  # Grace period for rendering changes
            else:
                errors.append("Could not isolate explicit submission element inside form target layout.")

            # 4. Evaluate submission state changes or visual success cues
            current_html = await page.content()
            current_html_lower = current_html.lower()
            success_keywords = ["thank you", "thanks", "submitted", "success", "received", "message sent"]
            
            if page.url != initial_url or any(kw in current_html_lower for kw in success_keywords):
                success = True
                messages.append("Submission confirmed: Browser redirected or matched visual success milestones.")
            else:
                errors.append("Form submission did not produce a visible success confirmation layout or route transition.")

        except Exception as e:
            errors.append(f"Runtime execution failure during contact form sequence: {str(e)}")

        return {
            "success": success,
            "errors": errors,
            "messages": messages,
            "timings": time.time() - start_time
        }